backend:
  name: github
  repo: duocifv/static-app   # thay bằng username/repo thật
  branch: main               # hoặc master nếu repo bạn dùng master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Sản phẩm"
    file: "products.json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Tên sản phẩm", name: "name", widget: "string" }
      - { label: "Giá", name: "price", widget: "number" }
      - { label: "Mô tả", name: "description", widget: "text" }
